spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  liquibase:
    change-log: db/changelog/changelog-master.yaml
  grpc:
    server:
      port: ${GRPC_SERVER_PORT:9090}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_EXTERNAL_URL}/realms/${KC_REALM}
          jwk-set-uri: ${KC_URL}/realms/${KC_REALM}/protocol/openid-connect/certs

cerbos:
  url: ${CERBOS_URL}

logging:
  level:
    org:
      bazar: ${LOGGING_LEVEL}
management:
  server:
    port: 9091