spring:

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bzrauthz}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  liquibase:
    change-log: db/changelog/changelog-master.yaml
  grpc:
    server:
      port: ${GRPC_SERVER_PORT:9090}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_URL:http://localhost:9999}/realms/${KC_REALM:bazar-realm}

cerbos:
  url: ${CERBOS_URL:localhost:3093}

logging:
  level:
    org:
      bazar: ${LOGGING_LEVEL:DEBUG}
management:
  server:
    port: 8090