ktor:
  deployment:
    port: 8090
  application:
    modules:
      - org.bazar.authorization.BazarAuthorizationApplicationKt.module
grpc:
  port: 9090
profile: ${PROFILE:LOCAL}
db:
  jdbcUrl: ${DB_URL:jdbc:postgresql://localhost:5432/bzrauthz}
  user: "postgres"
  password: "postgres"

auth:
  issuer: ${KC_ISSUER_URL:http://localhost:9999/realms/bazar-realm}
  jwkUrl: ${KC_JWK_URL:http://localhost:9999/realms/bazar-realm/protocol/openid-connect/certs}
  realm: "bazar-realm"

cerbos:
  url: ${CERBOS_URL:localhost:3593}
logging:
  level:
    root: INFO
    org:
      bazar: DEBUG
    jetbrains:
      exposed: DEBUG